### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "password": "123pedro"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pedro@gmail.com",
  "password": "123pedro"
}


### me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDkwYmM0Yy1iZWRhLTRhZmItYmMwOS02Y2Y0ZjE3MTIzYTQiLCJpYXQiOjE3Njc3NDk1MTYsImV4cCI6MTc2NzgzNTkxNn0.D9P6kyb_i-oJu_Z-QrCRFzYyxlmqId3z2ewFxAyFNHk


### esqueceu a senha
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "teste@teste.com"
}


### reset senha
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{ "code": "250055", "newPassword": "senha123" }

